Simplify integrity quotes structures
keylime/rust-keylime pull request #354
Opened 2022-03-23 14:22 UTC by ansasaki

Unify `KeylimeIdQuote`, `KeylimeIntegrityQuotePostAttestation`, and `KeylimeIntegrityQuotePostAttestation` structures into the single `KeylimeQuote` structure, using `Option` for optional fields.

2022-03-23 19:27 UTC, lkatalin requested changes
Nice, this is a much better way of doing it.
Two nits, one is an error message.

2022-03-24 10:19 UTC, ansasaki commented on src/quotes_handler.rs
> +                "Parameters should be strictly alphanumeric: {}",
Thanks, I'll fix it.

2022-03-24 10:26 UTC, ansasaki commented on src/quotes_handler.rs
> +    // If an index was provided, the request if for the entries starting from the given index
I'll fix this.

2022-03-24 14:08 UTC, lkatalin approved these changes

2022-03-24 14:08 UTC, merged