docker/fedora/keylime_rust.Dockerfile: add the logic of cloning and compiling rust-keylime
keylime/rust-keylime pull request #584
Opened 2023-05-11 02:29 UTC by hustliyilin

Obviously, the codes of the agent are located in the rust-keylime repository. However, there is no logic for cloning and compiling rust-keylime in the corresponding rust dockerfile. So we need to add it.

Signed-off-by: YiLin.Li <YiLin.Li@linux.alibaba.com>

2023-05-11 08:05 UTC, ansasaki commented on docker/fedora/keylime_rust.Dockerfile
> +make install
These changes will result in a huge layer in the resulting container as all intermediary compilation artifacts would be included in it (I mean many GB). Consider removing the artifacts after the installation (e.g. running `cargo clean`)

2023-05-11 09:14 UTC, hustliyilin commented
Thanks @ansasaki . After adding the `cargo clean` command, the docker image size reduce about 1.6GB.

2023-05-19 17:59 UTC, ansasaki requested changes

2023-05-19 17:59 UTC, ansasaki commented on docker/fedora/keylime_rust.Dockerfile
>  cp keylime.conf /etc/keylime.conf
Could you please remove this? It is not necessary anymore as we install the agent configuration in the `make install` step.

2023-05-24 01:35 UTC, hustliyilin commented
Thanks @ansasaki . I fixed it and  force-pushed the codes. Could you review it again?

2023-05-24 12:09 UTC, merged